### ISSUE TITLE
The specified cast from a materialized 'System.Int16' type to the byte type is not valid.

### ISSUE THREAD

**Issue by Aravind2601** [wiltondb/wiltondb#53]
Hi @staticlibs , 
we have column in our one of the table as 'tinyint' type and for mapping in csharp side we have byte enum like below. But we got error while mapping that column value.
   public enum Datavalue : byte
    {
        None = 0,
        One = 1,
        Two= 2,
        Three = 3
    }
Error: The specified cast from a materialized 'System.Int16' type to the byte type is not valid.
Could please help us on this?

**Comment by psrinivasa2** [comment]
Would it be possible to manually change (permanently) this column type in DB?
we are using tinyint in database, what would be the equivalent?

**Comment by staticlibs** [comment]
@psrinivasa2 

`tinyint` is the [correct type](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings) for .NET `byte`. But for some reason this column is returned as `smallint` (16 bit) in your case instead of `tinyint` (8 bit).

I can reproduce the problem only if I explicitly use `smallint` in DB and then try to read it as a .NET type `byte` with ADO.NET. When column is `tinyint` - then `GetByte` works correctly for me.

Can you check in Wireshark what `ColumnMetaData` is returned for the SQL query in your case? 

`tinyint` column should have the following metadata:

```
Token - ColumnMetaData
    Columns: 1
    Column 1
        Usertype: 0
        Flags: 0x0009
        Type: 38 (INTNTYPE)
        Type size: 1
        Column name length: 4
        Column Name: col1
```

And the `smallint` one (that seems to be returned in your case):

```
Token - ColumnMetaData
    Columns: 1
    Column 1
        Usertype: 0
        Flags: 0x0009
        Type: 38 (INTNTYPE)
        Type size: 2
        Column name length: 4
        Column Name: col1
```

**Comment by Aravind2601** [comment]
@staticlibs  yes we are getting meta data for  small int instead of tiny 
![image](https://github.com/user-attachments/assets/723f1aba-be0b-4751-a2bb-1c4b9a64cbbc)

**Comment by staticlibs** [comment]
@Aravind2601

This problem seems to be not easily reproducible, the mapping for your enum works fine for me with EF too:

```tsql
create table tab1 (
    id int,
    col1 tinyint
)
```

```csharp

using Microsoft.EntityFrameworkCore;

public class TestContext : DbContext
{
    const string connStr = "Server=DESKTOP-JS80C9O,1433;Initial Catalog=ef1;Integrated Security=True;Trust Server Certificate=true";
    public DbSet<Tab1> Tab1 { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options.UseSqlServer(connStr);
    }
}

public enum MyEnum : byte
{
    None = 0,
    One = 1,
    Two = 2,
    Three = 3
}

public class Tab1
{
    public int Id { get; set; }
    public MyEnum Col1 { get; set; }
}

class Program
{
    static void Main()
    {
        using var db = new TestContext();
        db.Add(new Tab1 { Id = 42, Col1 = MyEnum.One });
        db.SaveChanges();
        var tab1 = db.Tab1
            .OrderBy(b => b.Id)
            .First();
        Console.WriteLine(tab1.Col1);
    }
}
```
```
> dotnet run
One
```

Can you try to adapt this example closer to your app code to reproduce the problem?

**Comment by psrinivasa2** [comment]
Hi Alex,
![image](https://github.com/user-attachments/assets/0f62c3f3-707b-48a4-9c76-04969f60336e)

I have created a view with below definition, 

`CREATE VIEW dbo.TabViewTest
as
Select id, col1 from dbo.tab1
union all
select 11 as id, '' as col1`


After creating the above view, I looked at view definition in postgreSQL and see below 

`SELECT tab1.id,
    tab1.col1::smallint AS col1
   FROM test1_dbo.tab1
UNION ALL
 SELECT 11 AS id,
    '0'::smallint AS col1;`


I am not sure how smallint comes into picture, can you please check?

**Comment by psrinivasa2** [comment]
![{34939AB5-072C-4585-B4E9-30CEC0079CE9}](https://github.com/user-attachments/assets/d8a0dbed-98f7-45c4-b560-3b26e31e643d)

![{D455F791-B08D-489E-9C84-91E19D98D653}](https://github.com/user-attachments/assets/7a8de346-297c-4346-83d6-e3f988f19e7d)

**View**

create view dbo.TabView
as
select id, col1 from dbo.tab1
union all
select 11, '' as col1


**C# Code** 

using System;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Collections.Generic;
using System.Security.Cryptography;

namespace TinyInt_Type_Issue
{
	public class TestContext : DbContext
	{
		const string connStr = "Server=EHILP-503,2433;Initial Catalog=test1;Integrated Security=True;Trust Server Certificate=true";
		public DbSet<Tab1> Tab1 { get; set; }
		public DbSet<Tab1> TabView { get; set; }
		protected override void OnConfiguring(DbContextOptionsBuilder options)
		{
			options.UseSqlServer(connStr);
		}
	}

	public enum MyEnum : byte
	{
		None = 0,
		One = 1,
		Two = 2,
		Three = 3,
		Four = 4
	}

	public class Tab1
	{
		public int Id { get; set; }
		public MyEnum? Col1 { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			using var db = new TestContext();

			IQueryable<Tab1> query = from t in db.TabView
			select new Tab1
			{
				Id = t.Id,
				Col1 = t.Col1
			};

			Console.WriteLine(query.ToList().Count);
		}
	}
}



As mentioned above you can recreate the issue with above samples where the expected result is 14 and C# returns 13 in the sample application created with latest dotnet8 and latest entityframeworkcore

In our application the same scenario throws error of '
The specified cast from a materialized 'System.Int16' type to the byte type is not valid' where it is DotNetFramework 4.8 and EntotyFramework (not core).


In another place in our application, I could see the same error of 'The specified cast from a materialized 'System.Int16' type to the byte type is not valid' occurs when ternary operator is been used in LINQ query. 

Below throws error,

![{E17430C6-85A0-4EFE-B90B-3F956C9CA290}](https://github.com/user-attachments/assets/7cb047f5-cacf-40b6-9bb3-2fb9eb491794)

Below Works fine,

![{9918357C-B853-41FA-859F-1F683BCD36BE}](https://github.com/user-attachments/assets/5ff45f54-0410-4911-90ae-6f352db1542d)


Below also works fine,

![{DC8C2EA5-218F-4616-8662-568C8CBD8BF1}](https://github.com/user-attachments/assets/8b0ac035-a163-4d34-a254-245e46b8b822)



This is priority issue for us since it occurs in many places, can this be looked in @staticlibs, Alex?

**Comment by staticlibs** [comment]
@psrinivasa2

Sorry for delay, for some reason these two messages ([1](https://github.com/wiltondb/wiltondb/issues/53#issuecomment-2373523018), [2](https://github.com/wiltondb/wiltondb/issues/53#issuecomment-2373544722)) were not sent to me neither in email nor in GH notifications (and I am subscribed to this issue so it should not be necessary to tag me explicitly), so I only discovered them today. And they have all the information.

To clarify the problem:

For this table:

```tsql
create table tab1 (
    id int,
    col1 tinyint
)
```

The view defined the following way will have `col1` columns type as `int` in both MSSQL and Babelfish:

```tsql
create view view1 as
select id, col1 from tab1
union all
select 43 as id, 0 as col1
```

But if implicit conversion from `varchar` is used for `col1`, then MSSQL will coerce `col1` to `tinyint` and Babelfish will coerce it to `smallint`:

```tsql
create view view1 as
select id, col1 from tab1
union all
select 43 as id, '' as col1
```

And this causes the error in application because in EF `System.Int16` and `System.Byte` are two distinct types with no implicit conversion between them. And EF does not provide any easy way to allow to read the same property from either `tinyint` or `smallint` result-set columns.

The problem is that `tinyint` type in Babelfish [is implemented as a DOMAIN](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/63f90aabfcc0662454151699ac9494c9f703c7ca/contrib/babelfishpg_common/sql/numerics.sql#L1) over the `smallint`. `DOMAINs` are quite limited in Postgres, for example it is not possible to define a `CAST` from `varchar` to `tinyint` because [IMPLICIT CASTs](https://www.postgresql.org/docs/current/sql-createcast.html) to `DOMAINs` are not supported - underlying `smallint` type is always used. And problematic view relies on such implicit cast from `varchar` to `tinyint`.

Thus I cannot see any easy workaround inside the DB. It is possible to re-implement `tinyint` as an actual DB `TYPE` instead of a `DOMAIN`. But it is not clear whether this can be done in a way compatible with existing DB data. And also there is no point in implementing such change inside WiltonDB unless it is also accepted in upstream Babelfish (future versions of WiltonDB are supposed to support replication with Aurora - cannot have incompatible basic types). I will report this to Babelfish, they may have other ideas how to fix this, but I won't hold my breath that this is fixed there promptly.

Instead, would it be possible for you to apply the workaround in the DB schema or in app+DB schema:

1. change the view definition to use explicit cast to `tinyint` (to not rely on implicit conversion from `varchar`):

```tsql
create view view1 as
select id, col1 from tab1
union all
select 43 as id, cast(0 as tinyint) as col1
```

2. alternatively, change the `enum` definition to `short` and the corresponding table column definition to `smallint`:

```csharp
public enum MyEnum : short
{
    None = 0,
    ...
}
```

I understand that it may be quite a large task to change all such views in the codebase (or all enums and all corresponding tables in all existing deployments), but currently cannot see any other workarounds to this.

PS: also, can you please clarify this point:

> You can recreate the issue with above samples where the expected result is 14 and C# returns 13 in the sample application created with latest dotnet8 and latest entityframeworkcore

Do you mean that this example returns all records from `union all` on MSSQL but ignores the second part of `union all` on Babelfish? It does not run at all for me on Babelfish - fails with the same ` 'Unable to cast object of type 'System.Int16' to type 'System.Byte'.'` error. If there exist scenarios when this `tinyint` problem can cause wrong data (comparing to MSSQL) to be returned silently - this makes the issue much worse, I would like to have such scenario to bring it too to upstream Babelfish people.

**Comment by psrinivasa2** [comment]
![image](https://github.com/user-attachments/assets/9399b98e-4d71-46c8-a515-c8b5e47224ba)
  
Any idea on this scenario where ternary operation causing the same error?

**Comment by staticlibs** [comment]
@psrinivasa2 

The ternary operator in this query is translated to a `CASE` expression like this (`2` is an example of a byte value of `EMARSystemType` enum):

```tsql
SELECT
    <other_columns>, 
    CASE
        WHEN <subquery_result> IS NOT NULL
        THEN CAST(2 AS tinyint)
	ELSE NULL
    END AS [EMARSystemType]
FROM ...
```

This causes exactly the same problem like with `UNION` - the `NULL` (in `ELSE` branch) is being implicitly casted to `tinyint` and is casted to `smallint` instead.

As a workaround it is possible to define a T-SQL function to perform the explicit cast to `tinyint`:

```tsql
create function cast_to_tinyint (@value smallint)
returns tinyint
as begin
    return cast(@value as tinyint)
end
```

Then register it with EF (version specific, [EDMX](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd456812(v=vs.100)), [Core](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping)) and use like this:

```csharp
EMARSystemType = es != null ? es.EMARSystemType : MyEnumHelper.CastToTinyint(null),
```

Then EF will generate SQL like this (preventing the implicit cast problem):

```tsql
SELECT
    <other_columns>, 
    CASE
        WHEN <subquery_result> IS NOT NULL
        THEN CAST(2 AS tinyint)
	ELSE [dbo].[cast_to_tinyint](NULL)
    END AS [EMARSystemType]
FROM ...
```

**Comment by psrinivasa2** [comment]
Hi Alex,
The think is we will not migrate all of our customers to postgreSQL, mainly we are targeting customers who have size constraints with SQL Express edition. So the application layer should remain same for both SQL customers and PostgreSQL customers. Is there any way this can be handled in database layer instead of application layer which is common.

**Comment by staticlibs** [comment]
@psrinivasa2 

Application changes are necessary to work around this problem, because the application  currently generates SQL that relies on implicit casting to `tinyint`. It needs to be changed to either use explicit casts (with a user-mapped function) or to not use `tinyint` fields at all. In both cases changes to DB schema (either create a tinyint-casting T-SQL function or alter all tinyint columns in all tables to `smallint`) are required in both MSSQL and Babelfish (to keep the updated application compatible with both of them).

**Comment by psrinivasa2** [comment]
Hi Alex, 
We have around 1200 TinyInt columns in database and around 428 enum's with byte in C# code. 

Doing the application layers changing by identifying all the 428 enum's usage places with NULL condition will be a effortful work  and also the reason we consider to come to babelfish is no or very minimal application layer changes. If we go down this root, It will end up doing regression testing for both SQL and PostgreSQL and defeat the purpose.

With changing column type in SQL database layer, we have three database's and changing datatypes of 1200 columns for SQL and all 428 enum's pointing to short from byte is no guarantee on impact without regression effort in SQL. Moreover, we have control to change datatype only on one database out of three.

 _It is possible to re-implement tinyint as an actual DB TYPE instead of a DOMAIN. But it is not clear whether this can be done in a way compatible with existing DB data. And also there is no point in implementing such change inside WiltonDB unless it is also accepted in upstream Babelfish (future versions of WiltonDB are supposed to support replication with Aurora - cannot have incompatible basic types). I will report this to Babelfish, they may have other ideas how to fix this, but I won't hold my breath that this is fixed there promptly._

The above seems to be generic inside babelfish, Is this reported to babelfish and did we get any suggestion or generic workaround?

**Comment by psrinivasa2** [comment]
Please find sample POC application which not returns expected result and ignore union all result which I convey you above.

[TinyIntBabelFishIssueRecreate.zip](https://github.com/user-attachments/files/17184836/TinyIntBabelFishIssueRecreate.zip)



[TinyIntBabelFishIssueRecreate.zip](https://github.com/user-attachments/files/17184816/TinyIntBabelFishIssueRecreate.zip)

**Comment by staticlibs** [comment]
@psrinivasa2 

> Hi Alex, We have around 1200 TinyInt columns in database and around 428 enum's with byte in C# code.

I understand the scope of the problem, I think this is the worst Babelfish incompatibility I've seen so far. Perhaps in this case it will be better to go forward with implementing `tinyint` as a `TYPE` in WiltonDB and think about Aurora compatibility later. I will prototype such `TYPE` implementation and let you know whether this can solve the problem without changes in app layer.

> The above seems to be generic inside babelfish, Is this reported to babelfish and did we get any suggestion or generic workaround?

Reported it [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2987).

**Comment by staticlibs** [comment]
> Please find sample POC application which not returns expected result and ignore union all result which I convey you above.

M, I think this example is not correct (does not uncover the `tinyint` problem), it generates the following SQL for me:

```tsql
SELECT [t].[Id], [t].[Col1]
	FROM [Tab1] AS [t]
```

Basically it goes straight to the table and does not use the view (where union is used) at all.

**Comment by psrinivasa2** [comment]
okay, let me check again

**Comment by psrinivasa2** [comment]
Hi Alex,
One more generic query, so far the following four ticket has been fixed for our application related babelfish issues in WiltonDB. Last time when I check the Aurora postgreSQL in AWS , I could see these issues are exists there as well. Should I discuss with AWS team on fixing these issues on Aurora or It is already in sync with Aurora and only the deployment is pending there?

https://github.com/wiltondb/wiltondb/issues/28
https://github.com/wiltondb/wiltondb/issues/24
https://github.com/wiltondb/wiltondb/issues/23
https://github.com/wiltondb/wiltondb/issues/59

**Comment by staticlibs** [comment]
@psrinivasa2

I suggest to ask AWS support to provide the list of Aurora Babelfish versions where the particular defect is fixed (PR is applied), this is for defects that are already fixed in the latest public version. I don't know the exact process how older versions of Babelfish on Aurora are updated, I assume some of these updates may be not in the public repo. Also public Babelfish PRs on GitHub usually have AWS-internal issue references like `BABEL-4320` that may make it easier to find.

Corresponding upstream issues/PRs for WiltonDB issues you've listed:

 - #28 - [#1831](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/1831) `BABEL-4320`, fixed
 - #24 - [#2762](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2762), acknowledged
 - #23 - not reproducible on Linux, so Aurora is not affected
 - #59 - [#2944](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2944), not acknowledged

**Comment by staticlibs** [comment]
As an update on this, I've got the first draft of a `tinyint` implementation as a `TYPE` and can confirm that it allows to fix the problem with no changes on app side - implicit casts are handled correctly and `UNION`/`CASE` returns `tinyint` type with it. Current implementation is incomplete and the required scope (all required casts, operators, operator classes etc) for the complete `TYPE` impl is currently unclear - going to iterate on this. Backwards compatibility status is also currently unclear, can only confirm that it will work with a `pg_restore` (with `wdb_backup`) of an existing DB into a clean DB cluster.

**Comment by staticlibs** [comment]
@psrinivasa2 

I've prepared a test build [3.3-11-16-0-rc5](https://github.com/wiltondb/wiltondb/releases/tag/3.3-11-16-0-rc5) with the new `tinyint` implementation included. The implementation has a few bits missing (`tinyint` to floating point and `money` conversion, support for `tinyint` identity columns - needs couple of more days of work), but expected to cover the usage in your app. It would be great if you can try it on the use-cases that were failing before.

This version is test-only and requires a new DB cluster to be initialized. So, on the existing version, make backups of all DBs with `wdb_backup`. Then uninstall WiltonDB. Then remove or rename `C:\Program Files\WiltonDB Software\wiltondb3.3\data` directory and install new MSI. Then restore the backups with `wdb_backup`.

Internal representation of `tinyint` columns remains the same, so the update for existing DB clusters can be performed in theory, but such update script is yet to be written - only new DB clusters are supported for now. Also please note, that there is not going to be an update path from this test version - DB clusters created with it is only usable with it. Support for update from the older version is likely to be included in the stable release (with the final implementation of `tinyint`) - though this is not confirmed yet. Also this stable release update is currently blocked also by #65 - there is no point doing an update without fix for it included too.

Another thing is that this problem [was acknowledged by AWS people](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2987#issuecomment-2390860460), if they be able to fix it without new `TYPE` (that is a large change and update is non-trivial) - I will scrap the `TYPE` impl and include their fix into WiltonDB instead - will see how it goes.

**Comment by psrinivasa2** [comment]
Hi Alex,
Thanks, I will check this

**Comment by psrinivasa2** [comment]
What about below fixes?

https://github.com/wiltondb/wiltondb/issues/64

https://github.com/wiltondb/wiltondb/issues/62 And  https://github.com/wiltondb/wiltondb/issues/57

https://github.com/wiltondb/wiltondb/issues/59

https://github.com/wiltondb/wiltondb/issues/56

**Comment by psrinivasa2** [comment]
Facing issue with OS user login, though the relevant user created, It says not created.

![{58E990E4-16F9-4715-B9BC-798B423D86B6}](https://github.com/user-attachments/assets/1d089fbb-a929-40bf-8eb8-ff218565767d)

I will test the issues with wilton user for now

**Comment by staticlibs** [comment]
@psrinivasa2 

> #64

Not planned, this is not implemented in upstream Babelfish, the whole `rowversion` feature is considered not finished - `babelfishpg_tsql.escape_hatch_rowversion` flag exists for the reason.

> #62 

Fix going to be included into the update.

> #57

Already included into latest, going into update.

> #59

Fix going to be included into the update.

> #56

Extension files for `pgagent` are going to be included with WiltonDB MSI. `pgagent` service binaries are going to be packaged into a separate MSI after the update.

**Comment by psrinivasa2** [comment]
Hi Alex,
I am still not fullyclear on escape hatchs babelfish, helpful if you throw light on it. 

Setting the babelfishpg_tsql.escape_hatch_rowversion flag to ON is the workaround for this issue?

**Comment by psrinivasa2** [comment]
Shard you the mail for Test MSI installer observation with TinyInt change

**Comment by staticlibs** [comment]
@psrinivasa2 

> Setting the babelfishpg_tsql.escape_hatch_rowversion flag to ON is the workaround for ROWVERSION/TIMESTAMP issue?

Escape hatches are guarding the features that are not supported/implemented. `rowversion` implementation is incomplete, so it is behind the escape hatch.

**Comment by staticlibs** [comment]
@psrinivasa2 

> Shard you the mail for Test MSI installer observation with TinyInt change

Thanks for the details in email! In this case I can see a plain mapping of a field (not a ternary expression that is mapped to SQL `CASE`). So the problem is likely with a view that this model is mapped to? Can you share the relevant part of this view definition?

**Comment by psrinivasa2** [comment]
> @psrinivasa2
> 
> > Setting the babelfishpg_tsql.escape_hatch_rowversion flag to ON is the workaround for ROWVERSION/TIMESTAMP issue?
> 
> Escape hatches are guarding the features that are not supported/implemented. `rowversion` implementation is incomplete, so it is behind the escape hatch.

Hi Alex,
What we need to do from ourend to make this piece of scenario to work in our application?

**Comment by psrinivasa2** [comment]
> @psrinivasa2
> 
> > Shard you the mail for Test MSI installer observation with TinyInt change
> 
> Thanks for the details in email! In this case I can see a plain mapping of a field (not a ternary expression that is mapped to SQL `CASE`). So the problem is likely with a view that this model is mapped to? Can you share the relevant part of this view definition?

Shared you the views in mail Alex

**Comment by staticlibs** [comment]
@psrinivasa2 
 
> Hi Alex, What we need to do from ourend to make this piece of scenario to work in our application?

I suggest to exclude these `timestamp` columns from `INSERTs`, in EF it should be possible to do this using [DatabaseGeneratedOption.Computed](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.schema.databasegeneratedoption?view=net-8.0) annotation.

**Comment by staticlibs** [comment]
@psrinivasa2

> Shared you the views in mail Alex

M, I cannot reproduce the problem neither with `''` nor with `null`, the type `tinyint` is returned correctly for me:

```tsql
create table tab1 (
    id int,
    col1 tinyint
)

create view view1 as
select id, col1 from tab1
union all
select 43 as id, '' as col1

create view view2 as
select id, col1 from tab1
union all
select 44 as id, null as col1
```

Views column types:

```tsql
select data_type
from information_schema.columns
where table_name = 'view1'
and column_name = 'col1'
```
```
data_type
-----------------
tinyint
```

```tsql
select data_type
from information_schema.columns
where table_name = 'view2'
and column_name = 'col1'
```
```
data_type
---------------
tinyint
```

Does this only happen with more complicate views? Can you extend the example above to be closer to your tables structure to reproduce the problem?

**Comment by psrinivasa2** [comment]
Hi Alex,
If I drop and recreate those two views had the problem, the issue seems to be resolved. Are you able to guess any problem here?

**Comment by staticlibs** [comment]
@psrinivasa2 

> If I drop and recreate those two views had the problem, the issue seems to be resolved

Yes, this can explain this. The type of the columns for a view is recorded when view is created and stored in system catalogs. You can check it with the following query:

```tsql
select data_type
from information_schema.columns
where table_name = 'view1'
and column_name = 'col1'
```

In this case, due to the type implementation change and related cast rules changes, the output type of the query was fixed to be `tinyint`, but old incorrect `smallint` type was still recorded for this view. This is one of the incompatibilities that are caused by `tinyint` type change. Basically you need to do backup/restore for the test installer version with new `tinyint` type impl.

**Comment by psrinivasa2** [comment]
I followed below step, not sure how it is not solved the issue. Anyway fresh setup should work well, that should be fine for us, please go ahead on releasing the update with recent fixes.

_on the existing version, make backups of all DBs with wdb_backup. Then uninstall WiltonDB. Then remove or rename C:\Program Files\WiltonDB Software\wiltondb3.3\data directory and install new MSI. Then restore the backups with wdb_backup._

**Comment by staticlibs** [comment]
@psrinivasa2 

> I followed below step, not sure how it is not solved the issue

M, that can show a discrepancy between casts resolution when the view is created over TDS and over Postgres (how `pg_restore` is doing it) connections. I will re-check this point.

For now re-creating the schema and re-importing the data over TDS with `wdb_transfer` should definitely solve this.

**Comment by psrinivasa2** [comment]
Hi Alex @staticlibs , 
Waiting for the update release

**Comment by staticlibs** [comment]
@psrinivasa2 

Working on it, there are a few test failures from the last backports that need to be dealt with.

**Comment by psrinivasa2** [comment]
Hi Alex,
Where are we now?

**Comment by staticlibs** [comment]
@psrinivasa2 

Sorry for delay, being swamped by non-Babelfish tasks this week. If nothing happens, I should be able to complete all the backports and do the release on Monday.

**Comment by staticlibs** [comment]
@psrinivasa2 

Updated installer is available [here](https://github.com/wiltondb/wiltondb/releases/tag/3.3-11-16-0-rc6). It contains all the functional changes prepared for release (there are many more changes than initially intended - the fix for #65 had a long list of dependent changes), but is still marked as pre-release - there is no update script (that is not planned in your use-case) and there is a number of corner cases of `tinynt type` interaction with other types (`sqlvariant`, `datetime`) that still don't work correctly. None of these remaining `tinyint` problems are expected to affect your use case, otherwise I will be able to issue an update promptly. This version, despite named RC, is NOT experimental, all the changes there are intended for following versions and there is going to be the update path from it to the following releases.

**Comment by psrinivasa2** [comment]
Thanks much Alex, We will test this.

Can you share below issue fix for public babelfish reference to have discussion with AWS team.

[#62](https://github.com/wiltondb/wiltondb/issues/62)
[#57](https://github.com/wiltondb/wiltondb/issues/57)

**Comment by psrinivasa2** [comment]
> @psrinivasa2
> 
> > #64
> 
> Not planned, this is not implemented in upstream Babelfish, the whole `rowversion` feature is considered not finished - `babelfishpg_tsql.escape_hatch_rowversion` flag exists for the reason.
> 
> > #62
> 
> Fix going to be included into the update.
> 
> > #57
> 
> Already included into latest, going into update.
> 
> > #59
> 
> Fix going to be included into the update.
> 
> > #56
> 
> Extension files for `pgagent` are going to be included with WiltonDB MSI. `pgagent` service binaries are going to be packaged into a separate MSI after the update.

I could see description of release says only about TinyInt issue fix, what about abovr discussed?

![{DF60F01B-A349-4DED-A1DB-8945E2C304CD}](https://github.com/user-attachments/assets/003eb14b-af46-44de-9889-1f2dada34e2b)

**Comment by staticlibs** [comment]
@psrinivasa2 

Filed separate issues for these problems, will follow-up in them shortly:

>     1. UNION could not convert type "varchar" to tinyint

#78

>     2. Identity column type must be smallint, integer, or bigint

#75

>     3. Cross-db 'SELECT INTO' statement is not supported in Babelfish. As a workaround, consider running CREATE TABLE and INSERT-SELECT statements.

#79

**Comment by psrinivasa2** [comment]
Any idea why newly these issues are coming in?

**Comment by staticlibs** [comment]
@psrinivasa2 

Yes, for all of them, commenting in them now.

**Comment by staticlibs** [comment]
@psrinivasa2 

I've released the [update 12.16.1](https://github.com/wiltondb/wiltondb/releases/tag/3-lts-12-16-1) that includes fixes to all recently reported problems except #79 and #75 - see details in these issues.

For 12.16.1 MSI there is no update path from any previous version before the `tinyint` type chage. Because of this the default installation directory is changed from `C:\Program Files\WiltonDB Software\wiltondb3.3` to `C:\Program Files\WiltonDB Software\wiltondb_3_lts`. To perform the upgrade the DB cluster from thr 11.16-rc6 (the version from last Monday) it is necessary to apply the update for #78 ([link to comment](https://github.com/wiltondb/wiltondb/issues/78#issuecomment-2434576011)), then copy `C:\Program Files\WiltonDB Software\wiltondb3.3\data` directory into `C:\Program Files\WiltonDB Software\wiltondb_3_lts\data` and run the following:

```sql
ALTER EXTENSION "babelfishpg_common" UPDATE TO '3.3.5'
ALTER EXTENSION "babelfishpg_tsql" UPDATE TO '3.3.2'
```
